apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
    service: monitoring
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9100
    targetPort: 9100
  selector:
    app: node-exporter