apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter
    service: monitoring
  name: blackbox-exporter
spec:
  ports:
  - name: web
    port: 9115
    targetPort: 9115
  selector:
    app: blackbox-exporter
  type: LoadBalancer
  