apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
    service: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
      service: monitoring
  template:
    metadata:
      labels:
        app: blackbox-exporter
        service: monitoring
    spec:
      serviceAccount: blackbox-exporter
      volumes: 
      - name: config
        configMap:
          name: blackbox-exporter
      containers:
      - name: prometheus
        image: prom/blackbox-exporter:master
        args: [ '--config.file=/etc/blackbox-exporter/blackbox-exporter-config.yml' ] 
        ports:
        - containerPort: 9115
        volumeMounts:
        - name: config
          mountPath:  /etc/blackbox-exporter/
