apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
    service: monitoring
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
  selector:
    app: grafana
    service: monitoring
  sessionAffinity: None
  type: LoadBalancer