apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
    service: monitoring
  name: prometheus
spec:
  ports:
  - name: web
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus
  type: LoadBalancer
  