apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager
    service: monitoring
  name: alertmanager
spec:
  ports:
  - name: alertmanager1
    port: 9093
    targetPort: 9093
  - name: alertmanager2
    port: 9094
    targetPort: 9094
  selector:
    app: alertmanager
  type: LoadBalancer
